---
title: "WholeGBR"
author: "Eva Kovacs"
date: "01/02/2021"
output: html_document
---

## packages

```{r what you need }
install.packages("tidyverse")
install.packages("janitor")
install.packages("skimr")
install.packages("stringr")
install.packages("data.table")
install.packages("ggthemes")
install.packages("RColorBrewer")
install.packages("gmodels")
install.packages("dplyr")
install.packages("plyr")


library(tidyverse) # use install.packages("tidyverse") if receive an error message
library(janitor) # use install.packages("janitor") if receive an error message
library(skimr)  # use install.packages("skimr") if receive an error message
library(stringr) # use install.packages("stringr") if receive an error message
library(data.table)
library(ggthemes)
library(RColorBrewer)
library(gmodels)
library(dplyr)
library(plyr)

```


# Set the number of significant digits to preserve

```{r}

# Set
options(digits = 10)

#Check
options()

```

# FNGBR
# Create unique row numbers

```{r Creat unique row numbers}
# Read CSV files from folder

# Append regions
FNGBR_ALL <- dplyr::bind_rows(FNGBR_pred1,FNGBR_pred2)

FNGBR_ALL <- na.omit(FNGBR_ALL)

FNGBR_ALL <- FNGBR_ALL %>% dplyr::mutate(id = row_number())

# Make ID FNGBR specific
FNGBR_ALL <- FNGBR_ALL %>% dplyr::mutate(Region = as.character("FNGBR_"))

FNGBR_ALL <- FNGBR_ALL %>% unite("ID", Region:id, remove = TRUE)

FNGBR <- FNGBR_ALL %>%
  select("ID", "Longitude":"pred.Plat")

# write to CSV

FNGBR <- write.csv(FNGBR, file = "C:/Users/uqekovac/Documents/R/Coding/GBRBenthic2020/CoralTypeMapping/Wave_Predictions_per_region/FNGBR_ALL_simple.csv")

Far <- FNGBR

max(Far$pred.Bra)
max(Far$pred.Mass)
max(Far$pred.Plat)

min(Far$pred.Bra)
min(Far$pred.Mass)
min(Far$pred.Plat)

Far %>%
  summarise(
          
          mean_B = mean(pred.Bra, na.rm = TRUE),
          mean_M = mean(pred.Mass, na.rm = TRUE),
          mean_P = mean(pred.Plat, na.rm = TRUE)
          #sd = sd(pred.Bra),
          #sd = sd(pred.Mass),
          #sd = sd(pred.Plat)
          )

```

# ##############
# CCMR
# Create unique row numbers

```{r Creat unique row numbers}
# Read CSV files from folder

# Append regions

CCMR <- na.omit(CCMR_pred)

CCMR <- CCMR %>% dplyr::mutate(id = row_number())

# Make ID CCMR specific
CCMR <- CCMR %>% dplyr::mutate(Region = as.character("CCMR_"))

CCMR <- CCMR %>% unite("ID", Region:id, remove = TRUE)

CCMRa <- CCMR %>%
  select("ID", "pred.Bra":"pred.Plat")

# write to CSV

CCMR <- write.csv(CCMR, file = "C:/Users/uqekovac/Documents/R/Coding/GBRBenthic2020/CoralTypeMapping/Wave_Predictions_per_region/CCMR_simple.csv")

CC <- CCMRa

max(CC$pred.Bra)
max(CC$pred.Mass)
max(CC$pred.Plat)

min(CC$pred.Bra)
min(CC$pred.Mass)
min(CC$pred.Plat)

CC %>%
  summarise(
          
          #mean_B = mean(pred.Bra, na.rm = TRUE),
          #mean_M = mean(pred.Mass, na.rm = TRUE),
          #mean_P = mean(pred.Plat, na.rm = TRUE),
          sd = sd(pred.Bra),
          sd = sd(pred.Mass),
          sd = sd(pred.Plat)
          )

```

# ##############
# MKY
# Create unique row numbers

```{r Creat unique row numbers}
# Read CSV files from folder

# Append regions
MKY_ALL <- dplyr::bind_rows(MKY_preda, MKY_predb,MKY_predc,MKY_predd)

MKY_ALL <- na.omit(MKY_ALL)

MKY_ALL <- MKY_ALL %>% dplyr::mutate(id = row_number())

# Make ID MKY specific
MKY_ALL <- MKY_ALL %>% dplyr::mutate(Region = as.character("MKY_"))

MKY_ALL <- MKY_ALL %>% unite("ID", Region:id, remove = TRUE)

MKY <- MKY_ALL %>%
  select("ID", "pred.Bra":"pred.Plat")

# write to CSV

MKY <- write.csv(MKY, file = "C:/Users/uqekovac/Documents/R/Coding/GBRBenthic2020/CoralTypeMapping/Wave_Predictions_per_region/MKY_simple.csv")

MKY<- MKY_simple

max(MKY$pred.Bra)
max(MKY$pred.Mass)
max(MKY$pred.Plat)

min(MKY$pred.Bra)
min(MKY$pred.Mass)
min(MKY$pred.Plat)

MKY %>%
  summarise(
          
          mean_B = mean(pred.Bra, na.rm = TRUE),
          mean_M = mean(pred.Mass, na.rm = TRUE),
          mean_P = mean(pred.Plat, na.rm = TRUE),
          sd = sd(pred.Bra),
          sd = sd(pred.Mass),
          sd = sd(pred.Plat)
          )

```


# ##############
# TSV
# Create unique row numbers

```{r Creat unique row numbers}
# Read CSV files from folder

# Append regions
TSV_ALL <- dplyr::bind_rows(TSV_predda, TSV_preddb)

TSV_ALL <- na.omit(TSV_ALL)

TSV_ALL <- TSV_ALL %>% dplyr::mutate(id = row_number())

# Make ID TSV specific
TSV_ALL <- TSV_ALL %>% dplyr::mutate(Region = as.character("TSV_"))

TSV_ALL <- TSV_ALL %>% unite("ID", Region:id, remove = TRUE)

TSV <- TSV_ALL %>%
  select("ID", "pred.Bra":"pred.Plat")

# write to CSV

TSV <- write.csv(TSV, file = "C:/Users/uqekovac/Documents/R/Coding/GBRBenthic2020/CoralTypeMapping/Wave_Predictions_per_region/TSV_simple.csv")


max(TSV$pred.Bra)
max(TSV$pred.Mass)
max(TSV$pred.Plat)

min(TSV$pred.Bra)
min(TSV$pred.Mass)
min(TSV$pred.Plat)

TSV %>%
  summarise(
          
          #mean_B = mean(pred.Bra, na.rm = TRUE),
          #mean_M = mean(pred.Mass, na.rm = TRUE),
          #mean_P = mean(pred.Plat, na.rm = TRUE),
          sd = sd(pred.Bra),
          sd = sd(pred.Mass),
          sd = sd(pred.Plat)
          )

```






```{r}

# Try a density plot

Plot <- ggplot(CCb, aes(x=ID)) +
  geom_density()

ggsave("Plot.jpg", width = 22, height = 16, units = "cm", dpi = 300)


```

